### PR TITLE
Experiment 7A report

### PR DESCRIPTION
**Pull request by OmarTariq612**

### CODE REVIEW

**Comment by AbdulrhmnGhanem** [comment]
Good job!

Could you log the names of the sorahs with WER above q1? We need the names so we can collect more examples for these sorahs.

It should be something like that

||Muhammed Jibreel|Ghamadi|
|---|---|---|
|Q2|Al Fataha, Al Nas||
|Q3||The cow|
|Q4|Livestock|Livestock|
|Outliers|The star|The star, The Sprearders|

**Comment by OmarTariq612** [comment]
Now each sorah has its specific quartile and its name.

**Comment by AbdulrhmnGhanem** [comment]
You still need to generate the report, so we can start collecting more examples for these sorahs.

**Comment by OmarTariq612** [comment]
Now there is a seperate notebook [**sorahs-that-need-more-samples**](https://www.kaggle.com/code/omartariq612/sorahs-that-need-more-samples) notebook that takes the output of the [**analysis-and-visualization**](https://www.kaggle.com/code/omartariq612/analysis-and-visualization) notebook and generates the sorahs that need more samples (sorahs that their WER is not in the first quartile)

**Comment by AbdulrhmnGhanem** [comment]
You are confusing two things: the raw data, and the data report. I can't simply look at the JSON files, then take an action accordingly. You just need to add a cell or something at the end of this notebook.
Maybe even a simple `print(dataframe)` will be sufficient. The dataframe should the data represented in the table in the first comment.

**Comment by OmarTariq612** [comment]
Okay, here you are, a [colab notebook](https://colab.research.google.com/drive/1E4Z2tlFVGWO988e9SbNbObx921wNEx_O?usp=sharing) that prints the dataframe of the info in the **epoch-4** visualization.
I used colab because kaggle wasn't showing all the info in a viewable form, as you case see:
Screenshot from 2024-04-05 15-03-56

https://github.com/ElGarash/Al-Ajwad/assets/65053572/5a10a27a-b92a-41a5-94b9-11217a5b249d


https://github.com/ElGarash/Al-Ajwad/assets/65053572/0f074fa0-d192-469c-91d2-9d13cadc7e53

**Review by AbdulrhmnGhanem — APPROVED** [review]

**Pull request merged**
